---
title: "NEON forecast challenge submission"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-packages, echo = F, warning=F, message=F}
## install.packages('remotes')
## install.packages('fpp3') # package for applying simple forecasting methods
## install.packages('tsibble') # package for dealing with time series data sets and tsibble objects
## install.packages('tidyverse') # collection of R packages for data manipulation, analysis, and visualisation
## install.packages('lubridate') # working with dates and times
## remotes::install_github('eco4cast/neon4cast') # package from NEON4cast challenge organisers to assist with forecast building and submission

# Load packages
library(tidyverse)
library(lubridate)
library(tidymodels)
library(modeltime)
```

```{r get-targets, message=F}
#read in the targets data
targets <- read_csv('https://data.ecoforecast.org/neon4cast-targets/aquatics/aquatics-targets.csv.gz')

# read in the sites data
aquatic_sites <- read_csv("https://raw.githubusercontent.com/eco4cast/neon4cast-targets/main/NEON_Field_Site_Metadata_20220412.csv") |>
  dplyr::filter(aquatics == 1)

lake_sites <- aquatic_sites %>%
  filter(field_site_subtype == 'Lake')

# Filter the targets
targets <- targets %>%
  filter(site_id %in% lake_sites$field_site_id,
         variable == 'temperature')
```

```{r get-NOAA-past, message = F}

# Past stacked weather
noaa_past_s3 <- neon4cast::noaa_stage3()

variables <- c("air_temperature","air_pressure")
#Other variable names can be found at https://projects.ecoforecast.org/neon4cast-docs/Shared-Forecast-Drivers.html#stage-3

noaa_past <- noaa_past_s3  |> 
  dplyr::filter(site_id %in% lake_sites$field_site_id,
                datetime >= ymd('2017-01-01'),
                variable %in% variables) |> 
  dplyr::collect()

# aggregate the past to mean values
noaa_past_mean <- noaa_past |> 
  mutate(datetime = as_date(datetime)) |> 
  group_by(datetime, site_id, variable) |> 
  summarize(prediction = mean(prediction, na.rm = TRUE), .groups = "drop") |> 
  pivot_wider(names_from = variable, values_from = prediction) |> 
  # convert air temp to C
  mutate(air_temperature = air_temperature - 273.15)

```

```{r get-NOAA-future, message = F}
# Future weather
# New forecast only available at 5am UTC the next day
forecast_date <- Sys.Date() 
noaa_date <- forecast_date - days(1)

noaa_future_s3 <- neon4cast::noaa_stage2(start_date = as.character(noaa_date))
variables <- c("air_temperature","air_pressure")

noaa_future <- noaa_future_s3 |> 
  dplyr::filter(datetime >= forecast_date,
                site_id %in% lake_sites$field_site_id,
                variable %in% variables) |> 
  collect()

noaa_future_daily <- noaa_future |> 
  mutate(datetime = as_date(datetime)) |> 
  # mean daily forecasts at each site per ensemble
  group_by(datetime, site_id, parameter, variable) |> 
  summarize(prediction = mean(prediction)) |>
  pivot_wider(names_from = variable, values_from = prediction) |>
  # convert to Celsius
  mutate(air_temperature = air_temperature - 273.15) |> 
  select(datetime, site_id, air_temperature, parameter,air_pressure)
```


```{r model-setup}
# Generate a dataframe to fit the model to 
targets_lm <- targets |> 
  filter(variable == 'temperature') |>
  pivot_wider(names_from = 'variable', values_from = 'observation') |> 
  left_join(noaa_past_mean, 
            by = c("datetime","site_id"))
# Loop through each site to fit the model
temp_lm_forecast <- NULL

```

```{r forecast-loop, eval=FALSE}
forecast_horizon <- 35
forecast_dates <- seq(from = ymd(forecast_date), to = ymd(forecast_date) + forecast_horizon, by = "day")
n_members <- 31
for(i in 1:length(lake_sites$field_site_id)) {  
  
  example_site <- lake_sites$field_site_id[i]
  
  site_target <- targets_lm |>
    filter(site_id == example_site)

  noaa_future_site <- noaa_future_daily |> 
    filter(site_id == example_site)
  
  #Fit linear model based on past data: water temperature = m * air temperature + b

   fit <- lm(site_target$temperature ~ lag(site_target$air_temperature))
     fit_summary<-summary(fit)

  # fit <- lm(site_target$temperature ~ ....)
  coeffs <- round(fit$coefficients, 2)
  
  params_se <- fit_summary$coefficients[,2]
  
  param_df <- data.frame(beta1 = rnorm(31, coeffs[1], params_se[1]),
                       beta2 = rnorm(31, coeffs[2], params_se[2]))
  for (t in 1:length(forecast_dates)) {
  
  #pull driver ensemble for the relevant date; here we are using all 30 NOAA ensemble members
  site_drivers <- noaa_future_site %>%
    filter(datetime == forecast_dates[t])
  
  # use linear regression to forecast water temperature for each ensemble member
  # You will need to modify this line of code if you add additional weather variables or change the form of the model
  # The model here needs to match the model used in the lm function above (or what model you used in the fit)
  forecasted_temperature <- param_df$beta1 + param_df$beta2 * lag(site_drivers$air_temperature)+ rnorm(n = 31, mean = 0, sd = sd(fit$residuals,na.rm=TRUE))    
  # put all the relevant information into a tibble that we can bind together
  temperature <- tibble(datetime = rep(forecast_dates[t], times = n_members),
                         site_id = example_site,
                         parameter = 1:n_members,
                         prediction = forecasted_temperature,
                         variable = "temperature") #Change this if you are forecasting a different variable
  
  temp_lm_forecast <- dplyr::bind_rows(temp_lm_forecast, temperature)
  
  }
  message(example_site, ' temperature forecast run')
  
}
```

```{r proj1}
split <- initial_split(targets_lm, prop = 0.80, strata = site_id)
train_data <- training(split)
test_data <- testing(split)
our_recipe <- train_data |> 
  recipe(temperature ~ . ) |> 
  #step_rm(datetime) |>
  step_naomit(air_temperature, temperature, air_pressure)

our_model <- arima_reg(mode = "regression",
                       seasonal_period = NULL,
                       non_seasonal_ar = 2,
                       non_seasonal_differences = NULL,
                       non_seasonal_ma = NULL,
                       seasonal_ar = NULL,
                       seasonal_differences = NULL,
                       seasonal_ma = NULL
                       ) |> 
  set_engine("arima")

wflow <-
  workflow() |> 
  add_model(our_model) |> 
  add_recipe(our_recipe)

fit <- wflow |> 
  fit(data = train_data)

predictions <- predict(fit, new_data = test_data)

pred_test <- bind_cols(test_data, predictions)

multi_metric <- metric_set(rmse, rsq)

metric_table <- pred_test |> 
  multi_metric(truth = temperature, estimate = .pred)

metric_table


targets_future <- noaa_future_daily |> 
  mutate(temperature = NA,
         doy = yday(datetime))
new_predictions <- predict(fit, new_data = targets_future)


tidymodels_forecast <- data.frame()

for(i in unique(targets_future$parameter)){
  curr_ens <- targets_future |> 
    filter(parameter == i) |> 
    select(-parameter)
  
  new_predictions <- predict(fit, new_data = curr_ens)
  curr_ens <- bind_cols(curr_ens, new_predictions) |> 
    mutate(parameter = i)
  tidymodels_forecast <- bind_rows(tidymodels_forecast, curr_ens)
}

# tidymodels_forecasts_EFI |>
#   filter(variable == "temperature") |>
#   ggplot(aes(x = datetime, y = prediction, group = parameter)) +
#   geom_line() + 
#   facet_wrap(~site_id)
```

```{r make-standard}
# Make forecast fit the EFI standards
# Remember to change the model_id when you make changes to the model structure!
#my_model_id <- 'zim_proj1_example_ID'
tidymodels_forecasts_EFI <- tidymodels_forecast %>%
  rename(prediction = .pred) %>%
  mutate(variable = "temperature") |> 
  # For the EFI challenge we only want the forecast for future
  filter(datetime > Sys.Date()) %>%
  group_by(site_id, variable) %>%
  mutate(reference_datetime = min(datetime) - lubridate::days(1),
         family = "ensemble",
         model_id = "zimmerman_proj1",
         project_id="neon4cast") %>%
  select(model_id, datetime, reference_datetime, site_id, family, parameter, variable, prediction,project_id)

# temp_lm_forecast_EFI <- tidymodels_forecast |> 
#   filter(datetime > forecast_date) |> 
#   mutate(model_id = my_model_id,
#          reference_datetime = forecast_date,
#          family = 'ensemble',
#          parameter = as.character(parameter)) |> 
#   select(datetime, reference_datetime, site_id, family, parameter, variable, prediction, model_id)

```

```{r write-forecast}
# Write the forecast to file
theme <- 'aquatics'
date <- tidymodels_forecasts_EFI$reference_datetime[1]
forecast_name_1 <- paste0(tidymodels_forecasts_EFI$model_id[1], ".csv")
forecast_file_1 <- paste(theme, date, forecast_name_1, sep = '-')
forecast_file_1


if (!dir.exists('Forecasts')) {
  dir.create('Forecasts')
}

write_csv(tidymodels_forecasts_EFI, file.path('Forecasts',forecast_file_1))

neon4cast::forecast_output_validator(file.path('Forecasts',forecast_file_1))

```


```{r submit-forecast}

## # can uses the neon4cast::forecast_output_validator() to check the forecast is in the right format

#UNCOMMMENT THIS WHEN YOU ARE READY TO SUBMIT
neon4cast::submit(forecast_file = file.path('Forecasts', forecast_file_1),
                ask = FALSE) # if ask = T (default), it will produce a pop-up box asking if you want to submit


```

```{r plot-forecast}
tidymodels_forecasts_EFI |> 
  ggplot(aes(x=datetime, y=prediction, group = parameter)) +
  geom_line() +
  facet_wrap(~site_id) +
  labs(title = paste0('Forecast generated for ', tidymodels_forecasts_EFI$variable[1], ' on ', tidymodels_forecasts_EFI$reference_datetime[1]))
```